### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function fetchALL() on bool in C:\xampp\htdocs\test\index.php:127 Stack trace: #0 {main} thrown in C:\xampp\htdocs\test\index.php on line 127

### ISSUE THREAD

**Issue by Baca11** [ofarukcaki/dataleaks#12]
Fatal error: Uncaught Error: Call to a member function fetchALL() on bool in C:\xampp\htdocs\test\index.php:127 Stack trace: #0 {main} thrown in C:\xampp\htdocs\test\index.php on line 127

Please help, been stuck for hours.

**Comment by ofarukcaki** [comment]
Can you check if you have PDO extension installed with phpinfo?

**Comment by buittuan1985** [comment]
I installed PDO extension but not working

**Comment by Baca11** [comment]
Yes it is installed!

**Comment by Baca11** [comment]
Do you have a discord so I can contact you and show you? Thanks!

**Comment by buittuan1985** [comment]
> Do you have a discord so I can contact you and show you? Thanks!

Yes, Can you show me

**Comment by Baca11** [comment]
I need  ofarukcaki 's help....

**Comment by ofarukcaki** [comment]
I'll check this out, but nowadays it's not possible and it may take a while :s

**Comment by ofarukcaki** [comment]
Check https://github.com/ofarukcaki/dataleaks/issues/7#issuecomment-453233265

**Comment by Rolling20** [comment]
hello, i know you are probably busy, but i am confused as to set up a user. is there any way we can chat when you have some time? This looks like a really amazing application. thanks

**Comment by ofarukcaki** [comment]
Hello @rolling20, thanks for your interest. If you send me your Telegram id to contact@ofarukcaki.com we can have a chat in a proper time
