### ISSUE TITLE
Good but vulnerable to SQL injection.

### ISSUE THREAD

**Issue by doubledoze** [ofarukcaki/dataleaks#17]
Hello there !

This is a good project but its vulnerable to SQL Injection, be careful !!! (' OR '1'='1)

![image](https://user-images.githubusercontent.com/36266505/111784580-da708080-88bb-11eb-9868-31884aa11d38.png)

**Comment by ofarukcaki** [comment]
Hey! I'm actually surprised. Although I do not remember what I wrote, I remember that I pay attention to all possible SQLi scenarios while using PDO. Seems I wasn't careful 😅 

Thanks for letting everyone know about that.

**Comment by UndercoverHowardTheDuck** [comment]
LMAOOO XD
