### ISSUE TITLE
question

### ISSUE THREAD

**Issue by vertues** [ofarukcaki/dataleaks#3]
Hi! I dont see purchase.php, where is it? 

PS: your code is well written and very interesting ;)

**Comment by ofarukcaki** [comment]
Hey, purchase.php and affiliate.php are missing you're right. Hopefully, I will update the repo tomorrow night.

Thanks for your kind words, I'm glad you liked it.

**Comment by vertues** [comment]
Thanks for you answer! I hope to see the repo update quickly :p

**Comment by ofarukcaki** [comment]
I uploaded the missing 2 files, may be some compatibility issues with old files or so. Feel free to open an issue.

Btw welcome to Github :)
