### ISSUE TITLE
Database adding

### ISSUE THREAD

**Issue by CrypticKingJoe** [ofarukcaki/dataleaks#4]
Well I got users to work but how do I add database leaks?
do  need one table as 
username>email>password>ip
or something?

**Comment by ofarukcaki** [comment]
Hello @CrypticKingJoe, thank you for your interest in Dataleaks.

I added an example database to the repo, you can check it out! -> 9b5dd4769ce2e7c304aee3e099dc20b4b1646319

Make sure that do not use .(dot) in table names which causes trouble in SQL db, use _(underscore) instead. It will be printed as . on search results.

**Comment by CrypticKingJoe** [comment]
awesome thanks so much!
