### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function fetchALL() on boolean in

### ISSUE THREAD

**Issue by zhanggaoxuan** [ofarukcaki/dataleaks#7]
when use php 7.0, 7.1 and 7.2 will show this

**Comment by ghost** [comment]
make sure you have the pdo extension enabled

**Comment by Baca11** [comment]
Fatal error: Uncaught Error: Call to a member function fetchALL() on bool in C:\xampp\htdocs\test\index.php:127 Stack trace: #0 {main} thrown in C:\xampp\htdocs\test\index.php on line 127

Im not sure what the problem is please help!

**Comment by buittuan1985** [comment]
which is pdo enable? Can you show me

**Comment by ofarukcaki** [comment]
Create a phpinfo page and check if PDO is installed on your server

**How to create phpinfo:** https://serverpilot.io/docs/how-to-view-php-settings-with-phpinfo

**You should see something like this:** http://prntscr.com/m5jdve
